<?php

declare(strict_types=1);

namespace RoundlyConsulting\Crypto\Signature\Key;

use Closure;
use Illuminate\Contracts\Filesystem\Filesystem;
use Illuminate\Filesystem\LocalFilesystemAdapter;
use Illuminate\Support\Facades\Storage;
use InvalidArgumentException;
use RoundlyConsulting\Crypto\Signature\KeyLoadException;
use RuntimeException;
use SensitiveParameter;

/**
 * Shared plumbing for the opt-in Laravel loading factories (`fromStorage`,
 * `fromConfig`, `fromStorageOrGenerate`).
 *
 * These helpers deliberately touch Laravel's filesystem — the loaders are a
 * Laravel-native convenience on top of the zero-config core (`fromString` /
 * `generate` still work with no container, no config, no disk). The `config()`
 * read itself is NOT here: it stays inline in each `*FromConfig` factory so the
 * zero-config guard can scope config access precisely to those methods; this
 * trait only validates the value once it has been read.
 */
trait ReadsKeyMaterial
{
    /**
     * Read raw key material off a filesystem disk, or fail with a typed error —
     * whether the disk returns null for a missing file (the default) or throws
     * (a disk configured with `'throw' => true`), and for an unknown disk name.
     *
     * @throws KeyLoadException when the file is missing or the disk is unreadable or unknown
     */
    protected static function readFromStorage(string $disk, string $path): string
    {
        $filesystem = self::disk($disk);

        try {
            $contents = $filesystem->get($path);
        } catch (RuntimeException $e) {
            throw KeyLoadException::missingFile($disk, $path, $e);
        }

        if ($contents === null) {
            throw KeyLoadException::missingFile($disk, $path);
        }

        return $contents;
    }

    /**
     * Assert a value read from the consumer's config is a usable string. A blank
     * value (`''` or whitespace, what a host's `KEY=` gives) is not set, so it is
     * missing like an absent one. This never calls `config()`; the read lives in
     * the factory.
     *
     * @throws KeyLoadException when the config value is missing, blank, or not a string
     */
    protected static function requireConfigString(string $key, #[SensitiveParameter] mixed $value): string
    {
        if (! is_string($value) || trim($value) === '') {
            throw KeyLoadException::missingConfig($key);
        }

        return $value;
    }

    /**
     * @throws KeyLoadException when the disk is unknown
     */
    protected static function storageHas(string $disk, string $path): bool
    {
        return self::disk($disk)->exists($path);
    }

    /**
     * The key material at a disk path — generated by `$generate` and persisted
     * first when the file is missing.
     *
     * Concurrent first boots generate ONE key: generation runs under an
     * exclusive lock with the existence check repeated inside it, so a process
     * that lost the race adopts the winner's key instead of overwriting it. What
     * is returned is always what was read back from the disk, never the
     * in-memory copy that was written.
     *
     * @param  Closure(): string  $generate  fresh private key material
     *
     * @param-immediately-invoked-callable $generate
     *
     * @throws KeyLoadException when the disk is unknown, or the key cannot be locked, written, or read back
     */
    protected static function readOrGenerate(string $disk, string $path, Closure $generate): string
    {
        if (self::storageHas($disk, $path)) {
            return self::readFromStorage($disk, $path);
        }

        return self::whileLocked($disk, $path, static function () use ($disk, $path, $generate): string {
            if (! self::storageHas($disk, $path)) {
                self::persistPrivate($disk, $path, $generate());
            }

            return self::readFromStorage($disk, $path);
        });
    }

    /**
     * Persist private key material with restrictive visibility where the disk
     * supports it (0600-style perms on the local driver).
     *
     * On a local disk the key is never visible half-written or with open
     * permissions: it is written to a temporary file beside the key that is
     * created owner-only, given the disk's private visibility, then renamed
     * onto the key path in one step. A failure removes the temporary file, so
     * nothing is left behind for a later boot to adopt.
     *
     * NOTE: 'private' visibility is driver-dependent. On the local driver it maps
     * to owner-only file permissions; on some adapters (e.g. certain object
     * stores) it is a coarser ACL or a no-op. Only persist secret key material to
     * a disk you control that is private and local-permission-capable — never a
     * world-readable or publicly-served disk.
     *
     * A write that fails is an error, never a shrug: a generated key that was
     * not persisted would be replaced by a DIFFERENT one on the next boot, and
     * everything signed with this one would stop verifying.
     *
     * @throws KeyLoadException when the disk is unknown or the write fails
     */
    protected static function persistPrivate(string $disk, string $path, #[SensitiveParameter] string $contents): void
    {
        $filesystem = self::disk($disk);

        if ($filesystem instanceof LocalFilesystemAdapter) {
            self::writeLocalAtomically($filesystem, $disk, $path, $contents);

            return;
        }

        try {
            $written = $filesystem->put($path, $contents, 'private');
        } catch (RuntimeException $e) {
            throw KeyLoadException::unwritable($disk, $path, $e);
        }

        if ($written === false) {
            throw KeyLoadException::unwritable($disk, $path);
        }
    }

    /**
     * Run `$callback` holding an exclusive lock on the key at a disk path.
     *
     * A local disk's lock file sits beside the key (`<key>.lock`), so every
     * process — and every container — that shares the directory takes the same
     * lock. Any other disk can only be locked per host, through a lock file in
     * the system temp directory. The lock file is left in place: removing it
     * would let a waiting process lock a file that no longer has a name.
     *
     * @template T
     *
     * @param  Closure(): T  $callback
     * @return T
     *
     * @throws KeyLoadException when the lock file cannot be opened
     */
    private static function whileLocked(string $disk, string $path, Closure $callback): mixed
    {
        $filesystem = self::disk($disk);

        $lockFile = $filesystem instanceof LocalFilesystemAdapter
            ? self::localDirectory($filesystem, $disk, $path).'/'.basename($filesystem->path($path)).'.lock'
            : sys_get_temp_dir().'/crypto-key-'.hash('sha256', $disk."\0".$path).'.lock';

        $handle = @fopen($lockFile, 'c');

        if ($handle === false) {
            throw KeyLoadException::unlockable($disk, $path);
        }

        try {
            // Blocks until a rival's first boot has finished. A filesystem that
            // cannot lock at all still gets the re-check and the read-back.
            flock($handle, LOCK_EX);

            return $callback();
        } finally {
            flock($handle, LOCK_UN);
            fclose($handle);
        }
    }

    /**
     * @throws KeyLoadException when the temporary file cannot be created, written, made private, or renamed
     */
    private static function writeLocalAtomically(
        LocalFilesystemAdapter $filesystem,
        string $disk,
        string $path,
        #[SensitiveParameter] string $contents,
    ): void {
        $directory = self::localDirectory($filesystem, $disk, $path);
        $target = $directory.'/'.basename($filesystem->path($path));

        // tempnam() creates the file owner-only (0600), so the key is never on
        // disk with wider permissions. When it cannot write here it falls back
        // to the system temp directory, where a rename is no longer atomic.
        $temporary = @tempnam($directory, '.'.basename($target).'.');

        if ($temporary === false || dirname($temporary) !== $directory) {
            self::discard($temporary);

            throw KeyLoadException::unwritable($disk, $path);
        }

        $parent = dirname($path);
        $relative = ($parent === '.' ? '' : $parent.'/').basename($temporary);

        try {
            $written = @file_put_contents($temporary, $contents) === strlen($contents)
                && $filesystem->setVisibility($relative, 'private')
                && @rename($temporary, $target);
        } catch (RuntimeException $e) {
            self::discard($temporary);

            throw KeyLoadException::unwritable($disk, $path, $e);
        }

        if (! $written) {
            self::discard($temporary);

            throw KeyLoadException::unwritable($disk, $path);
        }
    }

    /**
     * The real, existing directory a local disk keeps the key in, created
     * through the disk (so its directory visibility applies) when missing.
     *
     * @throws KeyLoadException when the directory cannot be created
     */
    private static function localDirectory(LocalFilesystemAdapter $filesystem, string $disk, string $path): string
    {
        $directory = dirname($filesystem->path($path));

        try {
            $ready = is_dir($directory) || $filesystem->makeDirectory(dirname($path));
        } catch (RuntimeException $e) {
            throw KeyLoadException::unwritable($disk, $path, $e);
        }

        $real = $ready ? realpath($directory) : false;

        if ($real === false) {
            throw KeyLoadException::unwritable($disk, $path);
        }

        return $real;
    }

    private static function discard(string|false $temporary): void
    {
        if ($temporary !== false && is_file($temporary)) {
            @unlink($temporary);
        }
    }

    /**
     * @throws KeyLoadException when no disk of that name is configured
     */
    private static function disk(string $disk): Filesystem
    {
        try {
            return Storage::disk($disk);
        } catch (InvalidArgumentException $e) {
            throw KeyLoadException::unknownDisk($disk, $e);
        }
    }

    /**
     * Best-effort in-place wipe of a raw secret string when ext-sodium is
     * available. Passed by reference so the caller's own buffer is zeroed; PHP
     * cannot guarantee wiping (copy-on-write may leave other copies), so this is
     * defence-in-depth, not a guarantee.
     */
    protected static function wipeSecret(#[SensitiveParameter] string &$secret): void
    {
        if (! function_exists('sodium_memzero')) {
            return;
        }

        // Called through a plain callable so the wipe operates on our own buffer
        // without leaking sodium_memzero's "variable becomes null" semantics into
        // the non-nullable secret properties this zeroes.
        /** @var callable(string): void $memzero */
        $memzero = 'sodium_memzero';
        $memzero($secret);
    }
}
